Toy v1 infrastructure
QuTech-Delft/libqasm pull request #157
Opened 2023-08-18 13:49 UTC by rturrado

This initial commit brings ANTLR to play. We intend to use ANTLR for parsing cQASM 3.x files:
- Grammar files sit in the src/v3x folder.
- ANTLR C++ generator sits in the newly added 3rd_party folder. This is the Java generator used to create the C++ lexer and parser files. It's the latest version of the binary.
- ANTLR C++ runtime is requested as a dependency in conanfile.py.
- At src/CMakeLists.txt we first use the ANTLR generator to create the C++ lexer and parser files, and we then link against the ANTLR runtime.

This version of the library can only be built through conan. 
- This has been kind of a necessity because, on one hand, the ANTLR C++ runtime is quite easy to manage via conan, and, on the other hand, I haven't been able to make it work through ExternalProject_Add (the old FetchContent).
- But this move is positive in my opinion, something I was really after. I think I will improve build times since, for most cases (compiler/OS/platform), we will avoid to download and build dependencies (flex, bison, m4, ANTLR). Apart from decluttering the CMake files.

test.yml:
- Job steps are now: install python, install conan using python, install CMake, checkout, compile with conan, run tests.
- For cpp-arm64 MacOS we install bison, flex, gcc, java, and python. I've hit binary format problems when using the m4 and java packages from conanfile.py.
- For Conda I've removed the 'use-only-tar-bz2: true' setting because the conan 2.0.9 dependency is not a tar.bz2.
3rd_party/antr-4.13.0-complete.jar.
- Added. This is the Java binary used for generating the lexer and parser files with ANTLR.
cmake:
- Removed.  flex, bison and m4 are now installed via conan. For cpp-arm64 MacOS we need to install them via brew.
include/v3x, src/v3x:
- At the moment, these are just copies of include/v1x and src/v1x, changing the references to the v1x namespace for v3x.
- The cqasm-parse-helper implementation has been removed to avoid calls to the flex/bison parser. Implementing this class using the ANTLR parser will conform one of the next tasks in the "toy v1 implementation".
- cqasm_{lexer,parser}.g4 are the ANTLR grammar files for this "toy v1 language".
src/CMakeLists.txt:
- Removed references to the cmake folder. Although we are still requesting flex and bison packages, and of a given version.
- Added request for antlr4-runtime package, and updated include directories and link libraries to use this ANTLR C++ runtime.
- There is a big v3x section now that mimics the v1x section. Only that, in order to generate the lexer and parser files, it invokes the ANTLR generator.
- Updated compilation options. This is really not a necessary change, but it makes now libqasm resemble OpenQL (3 sections for the main 3 compilers, and same compilation options for gcc and clang).
test/CMakeLists.txt: 
- Updated compilation options. Same reason as above.
CMakeLists.txt:
- Added a few CMake policies to avoid compilation warnings.
conanfile.py:
- Added LIBQASM_CQASM_PYTHON_DIR, LIBQASM_PYTHON_DIR, LIBQASM_PYTHON_EXT, and PYTHON_EXECUTABLE options, since they are needed from setup.py.
- Added 3rd_party, python, res, and scripts folders to exports_sources. When we do a 'conan create' in order to install libqasm in the system, conan creates a folder in the conan cache for our package, then copies there all the needed stuff for the build, and builds and installs the package.
- Avoided installing flex, bison, and zulu-openjdk for armv8 architecture.
Dockerfile:
- Updated to install conan python package.
setup.py:
- Changed the CMake configure, build, and install command into a 'conan create' command.
- TODO: there is a piece of functionality that I've lost in the change, and it is the ability to specify CMAKE_INSTALL_PREFIX. I still have to look into this.

2023-09-04 08:56 UTC, pablolh requested changes
Nice!
I stopped in the midst of reviewing: someone starting drilling loudly next to our office :(
Will finish later

2023-09-04 08:56 UTC, pablolh commented on .github/workflows/test.yml
>    cpp-macos:
I think it is possible to merge the two jobs cpp-linux and cpp-macos, they do the same thing?

2023-09-04 08:56 UTC, pablolh commented on Dockerfile
> +    apt-get -qq -y install build-essential cmake git python3 python3-pip swig && \
Do you know where is this Dockerfile used?

2023-09-04 08:56 UTC, pablolh commented on conanfile.py
> +            self.tool_requires("zulu-openjdk/11.0.19")
Why don't we build the antlr parser on arm?

2023-09-04 08:56 UTC, pablolh commented on src/v3x/cqasm-analyzer.cpp
> +     * Helper for parsing a matrix. Highly templated to avoid repeating the
Let's not copy that...

2023-09-04 09:20 UTC, rturrado commented on scripts/generate_antlr_parser.py
> +    print("Usage: regenerate_parser.sh <INPUT FOLDER> <OUTPUT FOLDER>")
Done!

2023-09-04 09:25 UTC, rturrado commented on .github/workflows/test.yml
>    cpp-macos:
That's quite a fair point. Linux, MacOS, and Windows jobs are all the same except for the OS and compilers. I'll have a look if I can get it to work on a matrix such as `[ [Linux, g++], [Linux, clang++], MacOS, Windows]`.

2023-09-04 09:41 UTC, rturrado commented on conanfile.py
> +            self.tool_requires("zulu-openjdk/11.0.19")
I am pretty sure those last 2 lines are remnants of previous tests of mine and have to be removed.

The point is that the ANTLR generator has a Java JRE requirement, and I've tried to install that dependency via different ways. All of them proved to be not really portable:
- One way was to install ANTLR tools.
- Another one was to install a Conan package. This `zulu-openjdk` and another `openjdk` were the only packages I saw. `zulu-openjdk` seemed more portable. They say in their website that it should work on ARM, but I couldn't make it work for me.
- So, in the end, I'm just providing `3rd_party/antlr-4.13.0-complete.jar` with libqasm, and that file already includes the Java JRE.

For ARM we are building both the Flex/Bison and the ANTLR parsers. But we are installing the dependencies in a different way, e.g. directly via `brew`, because I have hit problems with the ARM versions of some Conan packages (`m4`, which is required by Flex/Bison, and `zulu-openjdk`, that is required by ANTLR).

These problems should be gone if we finally do these development (without flex/bison/antlr dependencies) and maintenance (with those dependencies) branches.

2023-09-04 09:54 UTC, rturrado commented on scripts/generate_antlr_parser.py
> +    jar_file_path = os.path.join(current_folder_path, "..", "3rd_party", "antlr-4.13.0-complete.jar")
It's not. :) At the moment, at least. Just to simplify things, I provide it within libqasm's `3rd_party` folder.

2023-09-04 09:55 UTC, rturrado commented on src/v3x/cqasm-analyzer.cpp
> +     * Helper for parsing a matrix. Highly templated to avoid repeating the
Same comment as above.

I wouldn't worry at all about these files at this point. They are not meant to stay there. They are just meant to let us compile, basically. Once we start implementing the v3 analyzer, and the different v3 `.tree` files, these files should change, be removed, whatever...

2023-09-04 09:57 UTC, rturrado commented on src/v3x/cqasm_parser.g4
> +array_indices: array_index (COMMA array_index)?;
Hm... I'm not sure. I thought it was for addressing various qubits at once. E.g. `breg[0, 2] = qreg[0, 2]` would read qubits 0 and 2 from the qubit register into bits 0 and 2 o the bit register.

2023-09-04 10:08 UTC, rturrado commented on Dockerfile
> +    apt-get -qq -y install build-essential cmake git python3 python3-pip swig && \
Not really. But I consider it a nice to have. For anyone having Docker on its machine, it would provide a way of running and testing libqasm in a kind of virtual environment (ephemeral or not).

2023-09-04 11:36 UTC, rturrado commented on .github/workflows/test.yml
>    cpp-macos:
Done! See GitHub Actions [here](https://github.com/QuTech-Delft/libqasm/actions/runs/6072555488/job/16472743346).

BTW, I've noticed we coud add, for free, gcc/MacOS and gcc/Windows to the set. Conan seems to detect those compilers in the GitHub runners.

2023-09-04 11:50 UTC, pablolh requested changes

2023-09-04 11:50 UTC, pablolh commented on 3rd_party/antlr-4.13.0-complete.jar
I wouldn't check in the .jar
I would download it in generate_antlr_parser.py instead

2023-09-04 11:50 UTC, pablolh commented on conanfile.py
> +            self.tool_requires("zulu-openjdk/11.0.19")
Those ANTLR tools would be installed only by people who want to build the library no? If so I think that's OK, if it's easier

2023-09-04 11:50 UTC, pablolh commented on src/v3x/cqasm_parser.g4
> +array_indices: array_index (COMMA array_index)?;
Oh right
So not multi-dimensional array but to select individual indices as a subset of all indices
Mmh I am not sure we need this to start with but we can discuss it this afternoon

2023-09-04 11:50 UTC, pablolh commented on include/v3x/cqasm-analyzer.hpp
> +/** \file
If they are meant to let us compile, then keep what's useful in it only, I would say
You can throw std::exception("Unimplemented") or return
It's a bit confusing to me if you add all of that with the intent of removing later

2023-09-04 16:32 UTC, rturrado commented on conanfile.py
> +            self.tool_requires("zulu-openjdk/11.0.19")
Not really. The ANTLR tools is directed mainly to developers, as it lets you print, as text or as a graphic, the AST resulting from a parse. From a user point of view, or an automated build point of view, it has the convenience that it saves you from 1) downloading the Java JRE, and 2) downloading the ANTLR jar. The downside I see is that it is quite a recent package, not that well maintained or updated, and not much portable.

2023-09-04 16:33 UTC, rturrado commented on src/v3x/cqasm_parser.g4
> +array_indices: array_index (COMMA array_index)?;
I can remove it from the toy implementation. No problem at all.

2023-09-04 16:35 UTC, rturrado commented on 3rd_party/antlr-4.13.0-complete.jar
OK. I think this should be pretty easy. We can do that at the Python script. Check for the jar file in a temporary directory and, if it's not there, download it.

2023-09-04 16:40 UTC, rturrado commented on include/v3x/cqasm-analyzer.hpp
> +/** \file
I see your point, yes. It makes completely sense. Let's try to keep it as clean and slim as possible from the very beginning.

2023-09-04 16:57 UTC, jvansomeren commented
I'm ok with all I saw.

Groet,

Hans van Someren
TU Delft, EWI QCE
Gebouw 36, Kamer 11.030
Tel +31 6 4298 2220




Op 4 sep. 2023 om 18:40 heeft Roberto Turrado Camblor ***@***.***> het volgende geschreven:

﻿

@rturrado commented on this pull request.

________________________________

In include/v3x/cqasm-analyzer.hpp<https://urldefense.com/v3/__https://github.com/QuTech-Delft/libqasm/pull/157*discussion_r1315113506__;Iw!!PAKc-5URQlI!5uUbzSbtHDrojcuyt9sBAC2ZDWEEIQY2IyPAT-_DixYsG6PkurQtMhj7aHmY0ANLgY9DV_SWQ_KAKwKif47mNsGUyxo7MJsC$>:

> @@ -0,0 +1,340 @@
+/** \file


I see your point, yes. It makes completely sense. Let's try to keep it as clean and slim as possible from the very beginning.

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/QuTech-Delft/libqasm/pull/157*discussion_r1315113506__;Iw!!PAKc-5URQlI!5uUbzSbtHDrojcuyt9sBAC2ZDWEEIQY2IyPAT-_DixYsG6PkurQtMhj7aHmY0ANLgY9DV_SWQ_KAKwKif47mNsGUyxo7MJsC$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AEDTBNSJ7VVUKMPU2OEGTQLXYYAA5ANCNFSM6AAAAAA3VR5R7A__;!!PAKc-5URQlI!5uUbzSbtHDrojcuyt9sBAC2ZDWEEIQY2IyPAT-_DixYsG6PkurQtMhj7aHmY0ANLgY9DV_SWQ_KAKwKif47mNsGUy3GWlDTy$>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-09-05 08:51 UTC, rturrado commented on 3rd_party/antlr-4.13.0-complete.jar
Done! See changes for this comment [here](https://github.com/QuTech-Delft/libqasm/commit/2211662f7de233087bd8159309897e047e26f936).

2023-09-05 08:53 UTC, rturrado commented on src/v3x/cqasm_parser.g4
> +array_indices: array_index (COMMA array_index)?;
Done! See changes for this comment [here](https://github.com/QuTech-Delft/libqasm/commit/02ccd98fbac084e1e8b64263bf7c226558497216).

2023-09-05 08:56 UTC, rturrado commented on scripts/generate_antlr_parser.py
> +    jar_file_path = os.path.join(current_folder_path, "..", "3rd_party", "antlr-4.13.0-complete.jar")
Removed. And changed to be downloaded at `scripts/generate_antlr_parser.py`. See changes for this comment [here](https://github.com/QuTech-Delft/libqasm/commit/2211662f7de233087bd8159309897e047e26f936).

2023-09-05 09:53 UTC, rturrado commented on include/v3x/cqasm-analyzer.hpp
> +/** \file
Done! I have removed almost everything. I've basically left a file implementing the API (for analyzing strings and files), but I have also needed to change the API to avoid using tree-gen classes.

I'm not at all convinced of this change though. My point here was to be able to rely on something (current implementation) in order to test the toy v1 implementation. I only wanted to implement `cqasm-parse-helper` to call ANTLR instead of Flex/Bison, but forgetting at the moment about the rest. For example, I could do the following test: analyze the same simple program from OpenQL, a program accepted by the toy v1 grammar, with the only difference of using a version 1.0 or 3.0. OpenQL would call the v1x or v3x analyzers, they would use Flex/Bison or ANTLR, and return a v1 or v3 `Program`.

2023-09-05 12:34 UTC, pablolh submitted a review, later dismissed

2023-09-05 14:06 UTC, rturrado commented on .github/workflows/test.yml
> +        exclude:
Good point, Pablo, thanks. I tried indeed to use a white list yesterday but I couldn't make it work. You can see this [commit](https://github.com/QuTech-Delft/libqasm/commit/4aafc335700d2c72c76683e1672c26db1df1c858), for example, and a few others after it, trying to use a white list. But I haven't used exactly what you propose, so I'll give it a go.

2023-09-05 14:07 UTC, rturrado commented on .github/workflows/test.yml
> +        name: Install bison, flex, gcc, java and python (MacOS)
Good point, thanks!

2023-09-05 15:19 UTC, pablolh submitted a review, later dismissed

2023-09-05 15:59 UTC, rturrado commented on .github/workflows/test.yml
> +        exclude:
I have tried again, now with your proposal, but it still doesn't like it. It seems that the use of a `compiler` in the `include` section is not considered if you don't have a `compiler` as a variable for the matrix as well, together with `os` and `build_type`. Of course, once you add `compiler` as a matrix variable, since you should define `g++`, `clang++`, and `msvc` as compilers, you need a black list. Or at least I haven't found an easy way to use a white list. What we can do, since the black list is less clear, is to add a comment stating the builds we want.

See [here](https://github.com/QuTech-Delft/libqasm/commit/7ccda38db0809d44aadb5776a190432db64bfee5) the changes for this comment, and [here](https://github.com/QuTech-Delft/libqasm/actions/runs/6085895087/job/16511026389) the builds generated for this job (they are 6 instead of 8, and they don't consider the `compiler`).

2023-09-05 16:02 UTC, rturrado commented on .github/workflows/test.yml
> +        name: Install bison, flex, gcc, java and python (MacOS)
Done! See the changes for this comment [here](https://github.com/QuTech-Delft/libqasm/commit/7ccda38db0809d44aadb5776a190432db64bfee5).

2023-09-05 21:13 UTC, pablolh approved these changes

2023-09-06 08:22 UTC, merged