Toy v1 parser implementation
QuTech-Delft/libqasm pull request #162
Opened 2023-09-20 23:33 UTC by rturrado

### ANTLR 2: visitors, error listeners

This is the second task on the cQASM 3.0 roadmap after the *Toy v1 infrastructure* (see PR #157).
It has allowed us to focus purely on implementing a minimal ANTLR parser without touching other aspects of the language.
The `cqasm-parse-helper` API:
- creates a `ScannerAntlr` that receives a `BuildCustomAstVisitor` and a `CustomErrorListener`, and then
- creates a `ParseHelper` that receives a `ScannerAdaptor`.
The `ScannerAntlr` class:
- parses an input stream to an ANTLR AST, and
- builds a tree-gen AST out of this ANTLR AST.
The `ParseHelper` class:
- invokes the `ScannerAntlr` to parse an input stream, and, whether,
- returns the tree-gen AST without errors, or
- catches any parsing exception and returns a null AST with some errors.

### Things we don't want in develop
- `res/v1x/test-v1x-parsing`: I needed something to test against. However *all those tests will be lost...*.
- `cqasm-analyzer.{hpp,cpp}`, `cqasm.{hpp,cpp}`, `cqasm-py.{hpp,cpp}`: I've removed the analyze functions that received only a file name or a data string from the `Analyzer`. This way, at a higher level, at `cqasm.hpp` or `cqasm.py.hpp`, I can call the Analyzer with a v1 or v3 parser. I.e. we can reuse the v1 Analyzer for the v3 parser. I understand we won't wont this functionality in the future.

### Things we definitely don't want in develop
- Commented out code:
  - `conanfile.py`: to be able to work with CLion's Conan Plugin.
  - `test/v1x/parsing.cpp`: to avoid doing semantic checks on the v3 files.
  - `CMakeLists.txt` files: adding of tests and subdirectories of tests.

### Things we do want in develop
- Changes to v1x parser:
  - Moved `ParseResult` to a separate file.
  - MInor aesthetic changes, like removing `../` from an include header when unnecessary.
- Changes to v3x parser:
  - Implementation of `ParseHelper`, build tree-gen AST visitor, custom error listener...
  - `generate_antlr_parser.py`: added a parameter to generate a base visitor class.
  - `Cqasm{Lexer,Parser}.g4`: renamed `cqasm_lexer.g4` and `cqasm_parser.g4` to `CqasmLexer.g4` and `CqasmParser.g4` as these texts are used as class names, and all ANTLR class names are written in camel case.
  - `CqasmParser.g4`: renamed expressions from snake case to camel case (for the same reason as above).
- `test/v1x/parsing.cpp`:
  - Removed dirent.h dependency. Used std::filesystem instead.
  - Fixed version comparison code? I should double check this. Is `version > cqasm::version::Version("1.2")` working properly?
- Use of `fmt::format` instead of standard streams in many places.
- Better naming. For example `flie_name` instead of `filename`, or `file_path` instead of `file_name` when the variable actually holds a path.

TODO
- Semantic checks: try enabling them in `parsing.cpp` for v3x. Also, see if they would require some changes in ANTLR.
- `ParseResult`: try changing `ParseHelper` so that it works with an interface containing a pointer to a generic AST, not to a tree-gen AST.

2023-09-22 16:02 UTC, pablolh requested changes
Wow!

2023-09-22 16:02 UTC, pablolh commented on src/v3x/cqasm-parse-helper.cpp
> +        result = scanner_up_->parse();
Those three classes are so small...
It looks a bit unnecessarily convoluted (I think not you but Jeroen)

2023-09-22 16:02 UTC, pablolh commented on src/v3x/cqasm-parse-helper.cpp
> +        result = scanner_up_->parse();
I with with a lambda would work as well
What do you think?

2023-09-22 16:37 UTC, rturrado commented on include/v3x/cqasm-parse-helper.hpp
> +    virtual ~ScannerAdaptor();
Good try! But not haha. It won't compile if you do that. I didn't keep the links to the explanations, both in Stack Overflow and in a C++ FAQ, but I had to write it this way.

2023-09-22 16:42 UTC, rturrado commented on include/v3x/BuildCustomAstVisitor.hpp
> +    std::any visitVersion(CqasmParser::VersionContext *context) = 0;
You mean, changing the signatures to `std::any visitVersion(CqasmParser::VersionContext *context) override;`? But then you would have to provide an implementation, wouldn't you?

2023-09-22 16:42 UTC, rturrado commented on include/v3x/cqasm-parse-helper.hpp
> +struct ScannerAdaptor {
They can definitely be moved to their own `.hpp` and `.cpp` files, yes. But I don't understand why they should go in an anonymous namespace. You mean, because they are not intended to be accessed from OpenQL customers? Like, for keeping them private?

2023-09-22 16:43 UTC, rturrado commented on src/cqasm-py.cpp
> +        [=](){ return cqasm::version::parse_string(data, filename); },
Ah OK, this is just copy-paste from old code. But, as I mentioned in the summary of the PR, this change is not meant to stay. Thanks!

2023-09-22 16:44 UTC, rturrado commented on src/v3x/BuildTreeGenAstVisitor.cpp
> +        ret = std::stoll(text);
Very good point! That was my first implementation hehe But `std::from_chars` for doubles is not implemented yet in clang, so I just rewrote this as this instead.

2023-09-22 16:46 UTC, rturrado commented on src/v3x/BuildTreeGenAstVisitor.cpp
> +    if (auto variable_ctx = context->VAR(); variable_ctx->getText() == "var") {
That was a last adding, yes. I wasn't sure ANTLR would check for that. I understand so, otherwise why would you write the grammar for? I will remove these checks. Thanks!

2023-09-22 17:05 UTC, rturrado commented on src/v3x/BuildTreeGenAstVisitor.cpp
> +    for (size_t i{ 0 }; i < context->expression().size(); ++i) {
Ooops! Thanks! I thought the Context API only allowed you to access each element via an index, e.g. `StatementContext* statement(size_t i);`. And for these cases where I need both index and element, I prefer the unsafer but clearer `for` loop. Changed.

2023-09-22 17:17 UTC, rturrado commented on src/v3x/cqasm-parse-helper.cpp
> +ScannerAntlrFile::ScannerAntlrFile(std::unique_ptr<BuildCustomAstVisitor> build_visitor_up,
The rationale here comes from a refactoring I did some time ago for the version parser, where it made more sense because each scanner (file or string) was doing more quite different things (Flex/Bison setup).

Anyway, having a look at the code again, and what it would mean to use functions instead of classes, whereas it is true that we would have less boilerplate code:
1) One option would be to construct a generic scanner holding both a file path or a data string. I don't like that. It forces you to check later what are you scanning, keeping a flag...
2) Another option would be to construct a generic scanner, without holding any information of what we want to parse, and then have two functions in `ParseHelper`, one that would call parse with a file, the other parse with a string. But apart from calling `parse_file_impl` or `parse_string_impl` in the generic scanner, they would share the rest of the code.
3) Trying to improve the latest version, you would come up with three functions at `ParseHelper`, a `parse_file`, a `parse_string`, and a `parse` that would hold the common code.

I think the current implementation is a better design.

2023-09-22 17:30 UTC, rturrado commented on src/v3x/cqasm-parse-helper.cpp
> +        result = scanner_up_->parse();
`ParseHelper` is small indeed, but important, as it is the place where we deal with both parse results and parse errors.

I don't think I would use lambdas as substitutes of other than calls, proxies...

On the other hand, if one has a look at the sequence of calls that are done when we analyze a file:
- `cqasm.cpp`: `analyze` function that calls the `default_analyzer` with two lambdas,
- `cqasm-parse-helper.cpp`: `parse_file` function, for example, that creates a `ParseHelper` and calls `parse` on it...

Well, it may surely be completely changed, but let's say I don't dislike it so much either.

If you have a look at `v1x/ParseHelper`, `v1x/cqasm-parse-helper.cpp` in general, you will see a lot has been refactored for `v3x`.

2023-09-22 17:41 UTC, rturrado commented on src/v3x/CqasmParser.g4
> +statement: mapping | variable | instruction;
OK! Thanks! I've just checked this [SO answer](https://stackoverflow.com/a/44306442/260313). I don't think they're really of use exactly there, because `mapping`, `variable`, and `instruction` will already have their `visitMapping`, `visitVariable`, and `visitInstruction` methods, but they can be of use when I refer to `INTEGER_LITERAL`, for example; in that case, I can generate a kind of alias and call it `IntegerLiteral`.

2023-09-22 17:47 UTC, rturrado commented on src/v3x/BuildTreeGenAstVisitor.cpp
> +        throw std::runtime_error{ "terminal node is out of the INTEGER_LITERAL range" };
I'm removing all that code. This is just still a lack of understanding on my side on what ANTLR lexer and parser are doing and what they are not. I believe that, when we get to this point, we cannot have anything that is not an integer literal. Otherwise the parser would have thrown an error during the ANTLR AST construction.

2023-09-22 17:49 UTC, rturrado commented on src/v3x/BuildTreeGenAstVisitor.cpp
> +    if (auto mapping_ctx = context->MAP(); mapping_ctx->getText() == "map") {
I think it is indeed enforced. I'm removing all these checks. On the other hand, I don't understand exactly why ANTLR contexts allow you to query `context->MAP()->getText()`.

2023-09-22 17:52 UTC, pablolh commented on include/v3x/BuildCustomAstVisitor.hpp
> +    std::any visitVersion(CqasmParser::VersionContext *context) = 0;
Isn't `visitVersion` declared in the base class CqasmParserVisitor?

2023-09-22 17:52 UTC, rturrado commented on src/v3x/BuildTreeGenAstVisitor.cpp
> +std::any BuildTreeGenAstVisitor::visitStatement(CqasmParser::StatementContext *context) {
Yes, the same here. The method for each option is right below this one. But I don't see how you would get rid of the checks. You don't have a function like `visit-my-child-whatever-it-is`.

2023-09-22 17:55 UTC, rturrado commented on include/v3x/BuildCustomAstVisitor.hpp
> +    std::any visitVersion(CqasmParser::VersionContext *context) = 0;
On the other hand, I would like to state that this class is also pure virtual. It's just an intermediate interface. So scanners build AST using visitors, but they let you build a tree-gen AST today, or a variant AST tomorrow.

2023-09-22 17:59 UTC, rturrado commented on include/v3x/BuildCustomAstVisitor.hpp
> +    std::any visitVersion(CqasmParser::VersionContext *context) = 0;
> Isn't `visitVersion` declared in the base class CqasmParserVisitor?

Yes, of course.

2023-09-22 18:00 UTC, pablolh commented on include/v3x/cqasm-parse-helper.hpp
> +struct ScannerAdaptor {
It's indeed to make them private since to me the only thing to expose here is parse_file and parse_string
The anonymous namespace allows one more thing.
If x.cpp has a definition for f in a non-anonymous namespace, and y.hpp declares f and links with x.cpp, that's valid but often an error
if f is defined in an anonymous namepace that is not possible
It's also a way to avoid accidentally violating one definition rule
Some details here https://stackoverflow.com/questions/154469/unnamed-anonymous-namespaces-vs-static-functions?noredirect=1&lq=

Note: if you keep those in the hpp, then there is no such problem, except that they are exposed while they should be purely implementation details I believe

2023-09-22 18:02 UTC, pablolh commented on src/v3x/BuildTreeGenAstVisitor.cpp
> +        ret = std::stoll(text);
Ah, I see
In fact now I remember running into the same thing sorry

2023-09-22 18:43 UTC, rturrado commented on src/v3x/CqasmParser.g4
> +statement: mapping | variable | instruction;
I've tried using it also for `INTEGER_LITERAL`, and I prefer to leave it like it is at the moment. However, I've understood the use of the labels. It may come handy in a future.

2023-09-22 19:57 UTC, rturrado commented on include/v3x/cqasm-parse-helper.hpp
> +struct ScannerAdaptor {
Thanks for the detailed explanations, Pablo!

I've tried using an anonymous namespace. Actually I did the same for the visitor and the error listener classes, since they should be even more private than the scanner.

However:
1) I got an error, saying something like that the `ParseHelper` class had a field whose type uses the anonymous namespace, and
2) I've had a look and we are not using anonymous namespaces anywhere in the code (well, this is not really a justification, but it tells us that we are not very much worried on showing too much).

Anyway, at least for the time being, I will keep these classes in `cqasm::v3x::parser`. Unless you convince me or show me how to make it work properly :) Do I maybe have to put the whole implementation of those anonymous classes in a cpp file?

Bear in mind also that they are just classes, not static functions.

2023-09-22 20:15 UTC, pablolh commented on include/v3x/BuildCustomAstVisitor.hpp
> +    std::any visitVersion(CqasmParser::VersionContext *context) = 0;
What's the difference between BuildCustomAstVisitor and CqasmParserVisitor?

2023-09-22 20:15 UTC, pablolh commented on src/v3x/CqasmParser.g4
> +statement: mapping | variable | instruction;
I think the thing I was thinking about was something like
```
statement:
MAP IDENTIFIER EQUAL expression # mapping
| VAR IDENTIFIER COLON IDENTIFIER # variable
| IDENTIFIER expressionList # instruction
;
```

modulo syntax errors

But it's all the same in the end I believe
Just, you wouldn't have to do this elseif chain I think

2023-09-22 20:15 UTC, pablolh commented on src/v3x/BuildTreeGenAstVisitor.cpp
> +        throw std::runtime_error{ "terminal node is out of the INTEGER_LITERAL range" };
I think you might need an error still no?
Your integer can be 09234892983475937457938492835984293847293852974829347293847
which doesn't fit into a 64 bits integer, but ANTLR won't check for that

2023-09-22 20:21 UTC, pablolh commented on include/v3x/cqasm-parse-helper.hpp
> +struct ScannerAdaptor {
That might change your whole file if you do that
I believe in that case ParseHelper class should also be in the cpp
And the only exposed things would be parse_file and parse_string

2023-09-22 20:22 UTC, pablolh commented on include/v3x/cqasm-parse-helper.hpp
> +struct ScannerAdaptor {
But I don't want to convince you, just showing how I would have done it, and I don't have authority :)
so if you want to keep it as is it's fine by me

2023-09-22 20:41 UTC, pablolh commented on src/v3x/cqasm-parse-helper.cpp
> +ScannerAntlrFile::ScannerAntlrFile(std::unique_ptr<BuildCustomAstVisitor> build_visitor_up,
As you've used, it looks like in C++ ANTLRFileStream is already child class of ANTLRInputStream, so I don't understand why you need another layer of class inheritance with those scanners, because those streams is the only place where you actually have a difference between file and string.

As I see it, parse_file creates a ANTLRFileStream  and passes it as pointer to a common parse function (which already exists in your code). parse_string creates an ANTLRInputStream which is passed as pointer to the same function, and then you use the already existing inheritance in ANTLR code.

I haven't tried it myself but it looks to me like the ANTLR api already caters for this problem of having shared parsing code from different sources

2023-09-22 20:49 UTC, rturrado commented on include/v3x/BuildCustomAstVisitor.hpp
> +    std::any visitVersion(CqasmParser::VersionContext *context) = 0;
`CqasmParserVisitor` is the class automatically generated by ANTLR. It's an inteface class that any visitor should implement. `BuildCustomAstVisitor` is a class that I have added, with the intention of being another interface that any AST builder visitor should implement. For example, a tree-gen AST builder, or a variant AST builder.

2023-09-22 22:18 UTC, rturrado commented on include/v3x/cqasm-parse-helper.hpp
> +struct ScannerAdaptor {
OK, then I will leave it like it is at the moment. I find it clearer separating hpp and cpp files. But I have to admit that I don't know yet enough about _unnamed namespaces_ and that they would be the proper solution here.

I've also seen that some projects use a namespace `detail` when they expose things as public but, at the same time, they want to hint the user that that code is internal.

I will keep an eye for the future on the use of namespaces. Thanks Pablo!

2023-09-25 08:28 UTC, rturrado commented on src/v3x/cqasm-parse-helper.cpp
> +ScannerAntlrFile::ScannerAntlrFile(std::unique_ptr<BuildCustomAstVisitor> build_visitor_up,
You could indeed create an `ANTLRInputStream` whether from a file or from a data string at `parse_file` or `parse_string` directly, and use it to construct an `AntlrScanner` but:
1) I tried some code keeping a reference to an stream in `AntlrFileScanner`, and I didn't like it. Dealing with streams to references makes the code quite more difficult. That was actually my first atttempt when writing this. So I've preferred, in this case, to just keep a file name and a string, and create the input stream just before the call to parse.
2) I don't really think `parse_file` or `parse_string` should be doing any ANTLR work, but just constructing a `ParseHelper` and call `parse` on it. So what I pursue here is separation of concerns, for ridiculous these classes can look like, dependency injection, better testability. To be honest, this is still doing things half way because, much probably, `parse_file` and `parse_string` should already receive an scanner and a `ParseHelper`, or not be implemented at all. But it's an approximation to what I'm after.

2023-09-26 23:20 UTC, rturrado commented on src/v3x/CqasmParser.g4
> +statement: mapping | variable | instruction;
I've done this change Pablo. I don't need anymore neither the `visitStatement` nor the `visitExpression` method. I don't save many lines using alternative labels for the `expression` rule, but the code is more elegant, since you get rid of those `if-else` sequences.

2023-09-26 23:26 UTC, rturrado commented
Hi Pablo,

I think I have addressed most of your comments. We still have to talk about what we want in `develop` from this PR:
- There are things here that are completely unrelated to the Toy v1 implementation and could be merged into `develop`.
- Other things, such as the current ANTLR grammar, or the tests, may go in but just considering that they would be soon rewritten for the MVP implementation.

2023-09-27 09:30 UTC, pablolh commented on include/v3x/BuildCustomAstVisitor.hpp
> +    std::any visitVersion(CqasmParser::VersionContext *context) = 0;
Those interfaces are identical right?
Then
1/ why redefine it?
2/ if you redefine it, why not just give it a new name, and let inheritance do its job, so you don't have to redeclare all the interface, since it's inherited?
Basically this would be enough:
`class BuildCustomAstVisitor : public CqasmParserVisitor {}` correct?

2023-09-27 09:31 UTC, pablolh approved these changes

2023-09-27 11:10 UTC, pablolh approved these changes

2023-09-27 11:18 UTC, pablolh approved these changes

2023-09-27 14:32 UTC, rturrado commented on src/v3x/BuildTreeGenAstVisitor.cpp
> +    auto text = node->getText();
Thanks Pablo! Added.

2023-09-29 09:01 UTC, pablolh submitted a review, later dismissed

2023-09-29 16:54 UTC, rturrado commented on include/v3x/BuildCustomAstVisitor.hpp
> +    std::any visitVersion(CqasmParser::VersionContext *context) = 0;
You're right. I'll change this.

2023-10-02 08:20 UTC, pablolh approved these changes

2023-10-02 08:33 UTC, merged