CQT 27: fix MacOS/x64 (with Python >= 3.11) wheels
QuTech-Delft/libqasm pull request #236
Opened 2024-07-26 12:27 UTC by rturrado

Issue:
We are generating universal instead of x86_64 binaries.
According to this [thread](https://github.com/pypa/wheel/issues/573), it's highly recommended to move to cibuildwheel as wheel creator.

Changes:
- Use cibuildwheel for generating the wheels.
- Remove support for Python 3.8 (the combo cibuildwheel/macos14/CPython 3.8 didn't work).
- Add pyproject.toml.
- Update setup.py: remove bdist, bdist_wheel, sdist, and egg_info.

2024-07-26 18:06 UTC, oschusler requested changes

2024-07-26 18:06 UTC, oschusler commented on setup.py
> +# TODO: I had to copy-paste get_version from version.py here
The code should not have todo's. If there is still work to be done, this should be in a ticket in the ticketing system

2024-07-26 18:06 UTC, oschusler commented on setup.py
> +#  because I couldn't get 'from version import get_version' work with pyproject.toml
What's with the pyproject.toml?

2024-07-26 18:06 UTC, oschusler commented on .github/workflows/assets.yml
> +        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
Where is the source code for deploying to TestPyPI?

2024-07-28 18:05 UTC, rturrado commented on setup.py
> +# TODO: I had to copy-paste get_version from version.py here
Good point. Thanks!

2024-07-28 18:13 UTC, rturrado commented on setup.py
> +# TODO: I had to copy-paste get_version from version.py here
I've removed the TODO and created issue #240.

2024-07-28 18:14 UTC, rturrado commented on setup.py
> +#  because I couldn't get 'from version import get_version' work with pyproject.toml
I've explained this in issue #240.

2024-07-28 18:15 UTC, rturrado commented on .github/workflows/assets.yml
> +        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
I've removed it. Copy-pasting here a comment I've just made in Jira.

> I’m sorry for the misundersandings and the confusion.
> 
> In my mail (24 Jul 2024, 16:13) I suggested dropping the TestPyPI step because, first, it was not behaving as I had expected, and second, it was giving me problems to set it up.
> 
> I didn’t understand that your response mail (25 Jul 2024, 21:34) was a negative to drop the TestPyPI step, but just an explanation of what you considered the value of using TestPyPI was. This is the complete contents of that mail, except for greetings:
> 
> > The goal however from deploying the packages to TestPyPI, never was about being able to test the released packages. For me, it is about testing whether the release actually succeeds.
> 
> There were two other facts that made me drop this step:
> 
> It wasn’t something required for this ticket. This ticket intends to fix a given libqasm build. But, since I planned to suggest creating a release after this ticket, I thought it would be good to have that publishing to TestPyPI in.
> 
> None of the cQASM tooling projects do a publishing to TestPyPI.
> 
> So, things to learn from this:
> 
> I should take more care deviating from the exact intents of each ticket. This can cause extra work, delays (not really lost work in this case, but it could be in other cases)…
> 
> I wouldn’t really add a TestPyPI step (maybe just because I still don’t understand neither its benefits, nor how to overcome its issues) but, if we want it, we can use another ticket for it.

2024-08-05 12:17 UTC, oschusler commented on setup.py
> +#  because I couldn't get 'from version import get_version' work with pyproject.toml
Tickets should be moved to Jira

2024-08-05 14:23 UTC, merged